#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
PROJECT_ROOT="$DIR/../"

#docker run --rm -it -v ${PROJECT_ROOT}:/usr/src/app kgalli/orchestrator $@
docker build -t kgalli/orchestrator -f ${PROJECT_ROOT}/Dockerfile  ${PROJECT_ROOT} > /dev/null
docker run --rm -it kgalli/orchestrator $@
