version: "3.8"
services:
  web:
    image: "kgalli/javalin-playground"
    ports:
      - "{HOST_PORT}:3000"

  api:
    image: "kgalli/javalin-playground"
    ports:
      - "{HOST_PORT}:8080"
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "kgalli"
      DB_PASSWORD: "kgalli"
      DB_DATABASE: "{DB_DATABASE}"
      DB_ENGINE: "postgresql"

  db:
    ports:
      - "{DB_PORT}:5432"
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: "{POSTGRES_PASSWORD}"
      POSTGRES_USER: "POSTGRES_USER"
