defaultEnvironment: "development"
environments:
  - development
  - test

services:
  web:
    repository_url: "github.com/kgalli/javalin-playground"
    source: "internal"
    environment_parameters:
      development:
        HOST_PORT: 3000
      test:
        HOST_PORT: 3000

  api:
    repository_url: "github.com/kgalli/javalin-playground"
    source: "internal"
    image_origin:
      source:
        # relative from checkout path
        # dockerfile: "Dockerfile"
        merge_properties:
          command: "java -jar /usr/src/app/app.jar"
      registry:
        image: "kgalli/javalin-playground"
    environment_parameters:
      development:
        HOST_PORT: 8080
        DB_DATABASE: "playground_dev"
      test:
        HOST_PORT: 9080
        DB_DATABASE: "playground_test"

  db:
    source: "external"
    environment_parameters:
      development:
        POSTGRES_PASSWORD: "kgalli"
        POSTGRES_USER: "kgalli"
      test:
        POSTGRES_PASSWORD: "kgalli"
        POSTGRES_USER: "kgalli"
