compose:
  networkName: "cliw"
  defaultEnvironment: "development"
  environments:
    - "development"
    - "test"
  services:
    - name: "api"
      repositoryUrl: "github.com/kgalli/javalin-playground"
      source: "internal"
      environments:
        default:
          ports:
            - "3000:3000"
          buildOrigin:
            source:
              build:
                context: "./javalin-playground"
                dockerfile: "Dockerfile"
              command: "java -jar /usr/src/app/app.jar"
            registry:
              image: "kgalli/javalin-playground"
        development:
          environment:
            DB_HOST: "db"
            DB_PORT: "5432"
            DB_USER: "kgalli"
            DB_PASSWORD: "kgalli"
            DB_DATABASE: "kgalli"
            DB_ENGINE: "postgresql"
        test:
          ports:
            - "3010:3000"
          environment:
            DB_HOST: "db"
            DB_PORT: "5432"
            DB_USER: "kgalli"
            DB_PASSWORD: "kgalli"
            DB_ENGINE: "postgresql"

    - name: "db"
      repositoryUrl: "https://github.com/docker-library/postgres"
      source: "external"
      environments:
        default:
          ports:
            - "9999:5432"
          buildOrigin:
            registry:
              image: "postgres"
          environment:
            POSTGRES_PASSWORD: "kgalli"
            POSTGRES_USER: "kgalli"
        development:
        test:
          ports:
            - "9998:5432"
    - name: "mysql"
      repositoryUrl: "https://github.com/docker-library/mysql"
      source: "external"
      environments:
        default:
          ports:
            - "8888:3306"
          buildOrigin:
            registry:
              image: mysql
              command: "--default-authentication-plugin=mysql_native_password"
              restart: always
          environment:
            MYSQL_ROOT_PASSWORD: kgalli
        development:
        test:
          ports:
            - "8887:3306"

dbTools:
  environments:
    - "development"
    - "test"
  defaultEnvironment: "development"
  dataSources:
    - name: "api"
      environments:
        development:
          host: "127.0.0.1"
          port: "9999"
          user: "kgalli"
          password: "kgalli"
          database: "kgalli"
          engine: "postgresql"
          readonly: false
        test:
          host: "127.0.0.1"
          port: "9998"
          user: "kgalli"
          password: "kgalli"
          database: "kgalli"
          engine: "postgresql"
          readonly: false
    - name: "mysql"
      environments:
        development:
          host: "127.0.0.1"
          port: "8888"
          user: "root"
          password: "kgalli"
          database: "kgalli"
          engine: "mysql"
          readonly: false
        test:
          host: "127.0.0.1"
          port: "8887"
          user: "root"
          password: "kgalli"
          database: "kgalli"
          engine: "mysql"
          readonly: false
