services:
  api:
    build:
      context: ./expressjs-playground
      dockerfile: Dockerfile
      target: builder
    volumes:
      - ./expressjs-playground/src:/usr/src/app/src
      - ./expressjs-playground/test:/usr/src/app/test
